// @ts-expect-error — generated by `opennextjs-cloudflare build`, absent until then.
import app from "../.open-next/worker.js";

import { serveVideo } from "./video";

/**
 * Entry point of durslel-web: the Next.js app, run by OpenNext on the Worker itself.
 *
 * Finished videos are answered from R2 before Next.js sees the request. Everything else — pages,
 * /api/solve, /api/pay — is the app. /api/render is bundled here too but never called here:
 * durslel-service reaches the renderer through its binding to dursel-web (wrangler.renderer.jsonc),
 * whose container has the subprocess and filesystem manim needs.
 */
export default {
  async fetch(request, env, ctx) {
    return (await serveVideo(env.VIDEOS, request)) ?? app.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<{ VIDEOS: R2Bucket }>;
